# Dockerfile.backend
FROM python:3.11-slim

WORKDIR /app

# Сначала зависимости — для кэширования
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Потом код
COPY . .

# Убедимся, что static/output существует
RUN mkdir -p /app/static/output

# Проверка: где uvicorn?
# RUN which uvicorn

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]